# Generated by Django 3.2.8 on 2021-11-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_names', '0002_rename_workout_name_workoutname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutname',
            name='user',
        ),
    ]
