# Generated by Django 3.2.8 on 2021-11-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20211108_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='custom_goal',
            field=models.CharField(default='I want to follow this program every week for 1 month.', max_length=250),
        ),
        migrations.AlterField(
            model_name='goal',
            name='selected_goal',
            field=models.CharField(default='Burn Fat and Lose Weight', max_length=100),
        ),
    ]
