# Generated by Django 3.2.8 on 2021-11-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75, null=True)),
                ('priority', models.CharField(blank=True, max_length=30, null=True)),
                ('plane', models.CharField(blank=True, max_length=50, null=True)),
                ('num_of_limbs', models.CharField(blank=True, max_length=50, null=True)),
                ('push_pull', models.CharField(blank=True, max_length=50, null=True)),
                ('body_part', models.CharField(blank=True, max_length=50, null=True)),
                ('up_low', models.CharField(blank=True, max_length=50, null=True)),
                ('hip_pos', models.CharField(blank=True, max_length=50, null=True)),
                ('agonist', models.CharField(blank=True, max_length=150, null=True)),
                ('antagonist', models.CharField(blank=True, max_length=150, null=True)),
                ('synergist', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
