# Generated by Django 3.2.8 on 2021-11-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='workout_name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
