# Generated by Django 3.2.8 on 2021-11-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_workout_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='workout_name',
            new_name='group',
        ),
    ]
