# Generated by Django 3.2.8 on 2021-11-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_rename_workout_name_exercise_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='antagonist',
            new_name='collection',
        ),
    ]
